baseurl = "https://tech.juan-cool.com"
DefaultContentLanguage = "en"
title = "卷儿的库"
# Using theme as git submodule
theme = "beautifulhugo"
# Or when using theme as hugo module
# theme = "github.com/halogenica/beautifulhugo"
#pygmentsStyle = "trac"
#pygmentsUseClasses = true
#pygmentsCodeFences = true
#pygmentsCodefencesGuessSyntax = true
#pygmentsUseClassic = true
#pygmentOptions = "linenos=inline"

[Services]
  [Services.Disqus]
    # Shortname = "XXX"
  [Services.googleAnalytics]
    # id = "XXX"

[Params]
  homeTitle = "卷爸随想" # Set a different text for the header on the home page
  subtitle = "Papa's records"
  mainSections = ["post","posts"]
  logo = "img/juanPapa.png" # Expecting square dimensions
  favicon = "img/juanPapa.ico"
  dateFormat = "January 2, 2006"
  commit = false
  rss = false
  comments = true
  readingTime = true
  wordCount = true
  selfHosted = true
#  useHLJS = true
  socialShare = false
  delayDisqus = true
  showRelatedPosts = true
#  cusdisID = "XXX" # Get your App id from cusdis.com
#  hideAuthor = true
#  gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"
#  disclaimerText = "The opinions expressed herein are my own personal opinions and do not represent my employer’s view in any way."

[Params.author]
  # Set only your "username" for default hosts and full URLs otherwise (e.g., "https://MyGitLab.org/username")
  name = "Wang"
  # website = "tech.juan-cool.com"
  # email = "youremail@qq.com"
  # github = "username"

[[menu.main]]
    name = "一堆记录"
    url = "post/一堆记录/"
    weight = 10

[[menu.main]]
    name = "About"
    url = "page/about/"
    weight = 40
