name: Deploy Hugo to Github Pages

on:
  push:
    branches:
      - master   # 当推送到 master 分支时触发（或根据需要修改为 main 等分支）
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. 检出仓库代码（含子模块，如果你使用了 Hugo 主题子模块）
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: true

    # 2. 设置 Hugo 环境（使用 peaceiris 提供的 action，可指定 Hugo 版本）
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest'   # 根据实际需求指定 Hugo 版本

    # 3. 构建 Hugo 站点，生成静态文件到默认的 public 目录
    - name: Build site with Hugo
      run: hugo --minify

    # 4. 部署到 GitHub Pages 分支（使用 peaceiris 提供的 gh-pages action）
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public

